-- MySQL Script generated by MySQL Workbench
-- Tue Nov  1 09:58:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Netchêflix
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Netchêflix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Netchêflix` DEFAULT CHARACTER SET utf8 ;
USE `Netchêflix` ;

-- -----------------------------------------------------
-- Table `Netchêflix`.`Distribuidoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Distribuidoras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Temporadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Temporadas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ano_lancamento` INT(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Midias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Midias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sinopse` TEXT(1000) NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `tipo` INT(1) NOT NULL,
  `pais_origem` VARCHAR(45) NULL,
  `avaliacao` DECIMAL(1,2) NULL,
  `idioma` VARCHAR(45) NULL,
  `qualidade` VARCHAR(10) NOT NULL,
  `classificacao` VARCHAR(45) NULL,
  `duracao` DECIMAL(4,2) NOT NULL,
  `arte` VARCHAR(45) NULL,
  `Distribuidoras_id` INT NOT NULL,
  `Temporadas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Midias_Distribuidoras1_idx` (`Distribuidoras_id` ASC) VISIBLE,
  INDEX `fk_Midias_Temporadas1_idx` (`Temporadas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Midias_Distribuidoras1`
    FOREIGN KEY (`Distribuidoras_id`)
    REFERENCES `Netchêflix`.`Distribuidoras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Midias_Temporadas1`
    FOREIGN KEY (`Temporadas_id`)
    REFERENCES `Netchêflix`.`Temporadas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Pessoas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Midias_has_Pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Midias_has_Pessoas` (
  `Midias_id` INT NOT NULL,
  `Pessoas_id` INT NOT NULL,
  PRIMARY KEY (`Midias_id`, `Pessoas_id`),
  INDEX `fk_Midias_has_Pessoas_Pessoas1_idx` (`Pessoas_id` ASC) VISIBLE,
  INDEX `fk_Midias_has_Pessoas_Midias_idx` (`Midias_id` ASC) VISIBLE,
  CONSTRAINT `fk_Midias_has_Pessoas_Midias`
    FOREIGN KEY (`Midias_id`)
    REFERENCES `Netchêflix`.`Midias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Midias_has_Pessoas_Pessoas1`
    FOREIGN KEY (`Pessoas_id`)
    REFERENCES `Netchêflix`.`Pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT(1000) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Prêmios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Prêmios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT(1000) NOT NULL,
  `ano` INT(4) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Midias_has_Prêmios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Midias_has_Prêmios` (
  `Midias_id` INT NOT NULL,
  `Prêmios_id` INT NOT NULL,
  PRIMARY KEY (`Midias_id`, `Prêmios_id`),
  INDEX `fk_Midias_has_Prêmios_Prêmios1_idx` (`Prêmios_id` ASC) VISIBLE,
  INDEX `fk_Midias_has_Prêmios_Midias1_idx` (`Midias_id` ASC) VISIBLE,
  CONSTRAINT `fk_Midias_has_Prêmios_Midias1`
    FOREIGN KEY (`Midias_id`)
    REFERENCES `Netchêflix`.`Midias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Midias_has_Prêmios_Prêmios1`
    FOREIGN KEY (`Prêmios_id`)
    REFERENCES `Netchêflix`.`Prêmios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Pessoas_has_Prêmios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Pessoas_has_Prêmios` (
  `Pessoas_id` INT NOT NULL,
  `Prêmios_id` INT NOT NULL,
  PRIMARY KEY (`Pessoas_id`, `Prêmios_id`),
  INDEX `fk_Pessoas_has_Prêmios_Prêmios1_idx` (`Prêmios_id` ASC) VISIBLE,
  INDEX `fk_Pessoas_has_Prêmios_Pessoas1_idx` (`Pessoas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoas_has_Prêmios_Pessoas1`
    FOREIGN KEY (`Pessoas_id`)
    REFERENCES `Netchêflix`.`Pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoas_has_Prêmios_Prêmios1`
    FOREIGN KEY (`Prêmios_id`)
    REFERENCES `Netchêflix`.`Prêmios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
