-- MySQL Script generated by MySQL Workbench
-- Tue Nov  1 20:06:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Netchêflix
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Netchêflix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Netchêflix` DEFAULT CHARACTER SET utf8 ;
USE `Netchêflix` ;

-- -----------------------------------------------------
-- Table `Netchêflix`.`Distribuidoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Distribuidoras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Episódios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Episódios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sinopse` TEXT(10000) NULL,
  `duracao` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Temporadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Temporadas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ano_lancamento` INT(4) NOT NULL,
  `Episódios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Temporadas_Episódios1_idx` (`Episódios_id` ASC) VISIBLE,
  CONSTRAINT `fk_Temporadas_Episódios1`
    FOREIGN KEY (`Episódios_id`)
    REFERENCES `Netchêflix`.`Episódios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Audios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Audios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Legendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Legendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma` VARCHAR(45) NOT NULL,
  `acessibilidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Midias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Midias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sinopse` TEXT(1000) NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `tipo` INT(1) NOT NULL,
  `pais_origem` VARCHAR(45) NULL,
  `avaliacao` DECIMAL(1,2) NULL,
  `idioma` VARCHAR(45) NULL,
  `qualidade` VARCHAR(10) NOT NULL,
  `classificacao` VARCHAR(45) NULL,
  `duracao` DECIMAL(4,2) NOT NULL,
  `arte` VARCHAR(45) NULL,
  `Distribuidoras_id` INT NOT NULL,
  `Temporadas_id` INT NOT NULL,
  `Audios_id` INT NOT NULL,
  `Legendas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Midias_Distribuidoras1_idx` (`Distribuidoras_id` ASC) VISIBLE,
  INDEX `fk_Midias_Temporadas1_idx` (`Temporadas_id` ASC) VISIBLE,
  INDEX `fk_Midias_Audios1_idx` (`Audios_id` ASC) VISIBLE,
  INDEX `fk_Midias_Legendas1_idx` (`Legendas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Midias_Distribuidoras1`
    FOREIGN KEY (`Distribuidoras_id`)
    REFERENCES `Netchêflix`.`Distribuidoras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Midias_Temporadas1`
    FOREIGN KEY (`Temporadas_id`)
    REFERENCES `Netchêflix`.`Temporadas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Midias_Audios1`
    FOREIGN KEY (`Audios_id`)
    REFERENCES `Netchêflix`.`Audios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Midias_Legendas1`
    FOREIGN KEY (`Legendas_id`)
    REFERENCES `Netchêflix`.`Legendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Pessoas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Midias_has_Pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Midias_has_Pessoas` (
  `Midias_id` INT NOT NULL,
  `Pessoas_id` INT NOT NULL,
  PRIMARY KEY (`Midias_id`, `Pessoas_id`),
  INDEX `fk_Midias_has_Pessoas_Pessoas1_idx` (`Pessoas_id` ASC) VISIBLE,
  INDEX `fk_Midias_has_Pessoas_Midias_idx` (`Midias_id` ASC) VISIBLE,
  CONSTRAINT `fk_Midias_has_Pessoas_Midias`
    FOREIGN KEY (`Midias_id`)
    REFERENCES `Netchêflix`.`Midias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Midias_has_Pessoas_Pessoas1`
    FOREIGN KEY (`Pessoas_id`)
    REFERENCES `Netchêflix`.`Pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT(1000) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Prêmios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Prêmios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT(1000) NOT NULL,
  `ano` INT(4) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Midias_has_Prêmios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Midias_has_Prêmios` (
  `Midias_id` INT NOT NULL,
  `Prêmios_id` INT NOT NULL,
  PRIMARY KEY (`Midias_id`, `Prêmios_id`),
  INDEX `fk_Midias_has_Prêmios_Prêmios1_idx` (`Prêmios_id` ASC) VISIBLE,
  INDEX `fk_Midias_has_Prêmios_Midias1_idx` (`Midias_id` ASC) VISIBLE,
  CONSTRAINT `fk_Midias_has_Prêmios_Midias1`
    FOREIGN KEY (`Midias_id`)
    REFERENCES `Netchêflix`.`Midias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Midias_has_Prêmios_Prêmios1`
    FOREIGN KEY (`Prêmios_id`)
    REFERENCES `Netchêflix`.`Prêmios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Pessoas_has_Prêmios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Pessoas_has_Prêmios` (
  `Pessoas_id` INT NOT NULL,
  `Prêmios_id` INT NOT NULL,
  PRIMARY KEY (`Pessoas_id`, `Prêmios_id`),
  INDEX `fk_Pessoas_has_Prêmios_Prêmios1_idx` (`Prêmios_id` ASC) VISIBLE,
  INDEX `fk_Pessoas_has_Prêmios_Pessoas1_idx` (`Pessoas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoas_has_Prêmios_Pessoas1`
    FOREIGN KEY (`Pessoas_id`)
    REFERENCES `Netchêflix`.`Pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoas_has_Prêmios_Prêmios1`
    FOREIGN KEY (`Prêmios_id`)
    REFERENCES `Netchêflix`.`Prêmios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Pessoas_has_Episódios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Pessoas_has_Episódios` (
  `Pessoas_id` INT NOT NULL,
  `Episódios_id` INT NOT NULL,
  PRIMARY KEY (`Pessoas_id`, `Episódios_id`),
  INDEX `fk_Pessoas_has_Episódios_Episódios1_idx` (`Episódios_id` ASC) VISIBLE,
  INDEX `fk_Pessoas_has_Episódios_Pessoas1_idx` (`Pessoas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoas_has_Episódios_Pessoas1`
    FOREIGN KEY (`Pessoas_id`)
    REFERENCES `Netchêflix`.`Pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoas_has_Episódios_Episódios1`
    FOREIGN KEY (`Episódios_id`)
    REFERENCES `Netchêflix`.`Episódios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Contas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ultimo_pagamento` DATETIME NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Perfis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NULL,
  `foto` BLOB NOT NULL,
  `Contas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Perfis_Contas1_idx` (`Contas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Perfis_Contas1`
    FOREIGN KEY (`Contas_id`)
    REFERENCES `Netchêflix`.`Contas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Pagamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor_pago` DECIMAL(3,2) NOT NULL,
  `vencimento` DATETIME NULL,
  `data_pagamento` DATETIME NOT NULL,
  `valor_devido` DECIMAL(3,2) NULL,
  `Contas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pagamentos_Contas1_idx` (`Contas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamentos_Contas1`
    FOREIGN KEY (`Contas_id`)
    REFERENCES `Netchêflix`.`Contas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Planos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(3,2) NULL,
  `qualidade_maxima` INT(1) NOT NULL,
  `Contas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Planos_Contas1_idx` (`Contas_id` ASC) VISIBLE,
  CONSTRAINT `fk_Planos_Contas1`
    FOREIGN KEY (`Contas_id`)
    REFERENCES `Netchêflix`.`Contas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Netchêflix`.`Acessos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Netchêflix`.`Acessos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `salvar` TINYINT NOT NULL,
  `timestamp` VARCHAR(5) NULL,
  `Midias_id` INT NOT NULL,
  `Perfis_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Acessos_Midias1_idx` (`Midias_id` ASC) VISIBLE,
  INDEX `fk_Acessos_Perfis1_idx` (`Perfis_id` ASC) VISIBLE,
  CONSTRAINT `fk_Acessos_Midias1`
    FOREIGN KEY (`Midias_id`)
    REFERENCES `Netchêflix`.`Midias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Acessos_Perfis1`
    FOREIGN KEY (`Perfis_id`)
    REFERENCES `Netchêflix`.`Perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
